<a href="https://colab.research.google.com/github/neohack22/Datascience-Seminaire-Exercices/blob/main/Exercice_de_1_2_NumpyCrashCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Retrouver pour chaque sortie l'instruction correspondante.



```
import numpy as np
my_list = [1,2,3]
```



##### array([1, 2, 3])

array([1, 2, 3])

##### numpy.ndarray

numpy.ndarray

##### array([1, 2, 3])

array([1, 2, 3])

##### array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### array([ 0,  2,  4,  6,  8, 10])

array([ 0,  2,  4,  6,  8, 10])

##### array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

##### array([[0., 0., 0., 0., 0.], [0., 0., 0., 0., 0.], [0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##### array([1., 1., 1.])

array([1., 1., 1.])

##### array([[1., 1., 1., 1., 1.], [1., 1., 1., 1., 1.], [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

##### array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444, 0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        , 1.11111111,  1.22222222,  1.33333333,  1.44444444,  1.55555556, 1.66666667,  1.77777778,  1.88888889,  2.        ,  2.11111111, 2.22222222,  2.33333333,  2.44444444,  2.55555556,  2.66666667, 2.77777778,  2.88888889,  3.        ,  3.11111111,  3.22222222, 3.33333333,  3.44444444,  3.55555556,  3.66666667,  3.77777778, 3.88888889,  4.        ,  4.11111111,  4.22222222,  4.33333333, 4.44444444,  4.55555556,  4.66666667,  4.77777778,  4.88888889, 5.        ,  5.11111111,  5.22222222,  5.33333333,  5.44444444, 5.55555556,  5.66666667,  5.77777778,  5.88888889,  6.        , 6.11111111,  6.22222222,  6.33333333,  6.44444444,  6.55555556, 6.66666667,  6.77777778,  6.88888889,  7.        ,  7.11111111, 7.22222222,  7.33333333,  7.44444444,  7.55555556,  7.66666667, 7.77777778,  7.88888889,  8.        ,  8.11111111,  8.22222222, 8.33333333,  8.44444444,  8.55555556,  8.66666667,  8.77777778, 8.88888889,  9.        ,  9.11111111,  9.22222222,  9.33333333, 9.44444444,  9.55555556,  9.66666667,  9.77777778,  9.88888889, 10.        , 10.11111111, 10.22222222, 10.33333333, 10.44444444, 10.55555556, 10.66666667, 10.77777778, 10.88888889, 11.])

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ,
        1.11111111,  1.22222222,  1.33333333,  1.44444444,  1.55555556,
        1.66666667,  1.77777778,  1.88888889,  2.        ,  2.11111111,
        2.22222222,  2.33333333,  2.44444444,  2.55555556,  2.66666667,
        2.77777778,  2.88888889,  3.        ,  3.11111111,  3.22222222,
        3.33333333,  3.44444444,  3.55555556,  3.66666667,  3.77777778,
        3.88888889,  4.        ,  4.11111111,  4.22222222,  4.33333333,
        4.44444444,  4.55555556,  4.66666667,  4.77777778,  4.88888889,
        5.        ,  5.11111111,  5.22222222,  5.33333333,  5.44444444,
        5.55555556,  5.66666667,  5.77777778,  5.88888889,  6.        ,
        6.11111111,  6.22222222,  6.33333333,  6.44444444,  6.55555556,
        6.66666667,  6.77777778,  6.88888889,  7.        ,  7.11111111,
        7.22222222,  7.33333333,  7.44444444,  7.55555556,  7.66

array([0.00000000e+00, 2.20044009e-03, 4.40088018e-03, ...,
       1.09955991e+01, 1.09977996e+01, 1.10000000e+01])

4

2

713

array([[  7, 919, 780],
       [172, 608, 147],
       [881, 166, 273]])

In [ ]:
np.random.normal

<function RandomState.normal>

*   `random` : module au sein de numpy spécialement conçu pour générer des nombres aléatoires.
*   `normal` : fonction au sein du module `random` qui génère des nombres aléatoires à partir d'une **distribution normale**, également appelée **distribution gaussienne**. Cette distribution est couramment utilisée en statistique et en probabilité en raison de sa courbe en forme de cloche.

`np.random.normal` **en elle-même ne génère aucun nombre aléatoire**. Elle fait simplement référence à la fonction qui peut être utilisée pour les générer. Pour obtenir réellement des nombres aléatoires à partir d'une distribution normale, vous devrez appeler cette fonction avec des paramètres spécifiques, comme la moyenne (centre) et l'écart type (dispersion) de la distribution.

Par exemple, pour générer 10 nombres aléatoires à partir d'une distribution normale avec une moyenne de 0 et un écart type de 1, vous utiliseriez :


`np.random.normal(loc=0, scale=1, size=10)`

Par exemple, les modèles dits génératifs génèrent des distributions de probabilités, qui sont ensuite utilisées pour générer de nouvelles données :

1.   **Apprentissage de la distribution** : Pendant l'entraînement, le modèle apprend la distribution de probabilité des données d'entrée (dans le cas de GPT, du texte). Il apprend par exemple la probabilité d'apparition d'un mot après une séquence de mots donnée.

2.   **Prédiction de la prochaine donnée** : Lorsqu'on lui demande de générer du texte, le modèle utilise sa connaissance de la distribution pour prédire la prochaine donnée (le prochain mot, caractère, etc.). Il calcule la probabilité de chaque option possible et choisit celle qui a la plus haute probabilité.

3.   **Génération itérative** : Ce processus est répété de manière itérative, en utilisant la donnée nouvellement générée comme contexte pour prédire la suivante. C'est ainsi que le modèle construit des séquences de données (des phrases, des paragraphes, etc.).

4.   **Echantillonnage** : Il est important de noter que le modèle ne choisit pas toujours l'option la plus probable. Il peut également **échantillonner** à partir de la distribution, c'est-à-dire choisir une option au hasard en fonction de sa probabilité. Cela permet au modèle de générer des données plus variées et créatives, et d'éviter de se répéter constamment.

En résumé:

*   Le modèle **ne crée pas de nouvelles données à partir de rien**. Il utilise les données d'entraînement pour apprendre une distribution de probabilité.
*   Il utilise cette distribution pour **prédire la prochaine donnée** dans une séquence, soit en choisissant l'option la plus probable, soit en échantillonnant à partir de la distribution.
*   La génération de nouvelles données est donc un** processus itératif** basé sur des prédictions probabilistes.

On peut dire que le modèle génère des distributions de probabilités qui servent de "recette" pour créer de nouvelles données. C'est cette "recette" qui est apprise pendant l'entraînement, et qui permet au modèle de générer des données similaires à celles qu'il a vues.



---



In [ ]:
np.random.seed(101)
print(np.random.randint(0,100,10))

[95 11 81 70 63 87 75  9 77 40]
[ 4 63 40 60 92 64  5 12 93 40]


`seed()` : est utilisée pour "amorcer" le générateur de nombres aléatoires. Imaginez que vous plantez une graine spécifique pour une plante - cela garantit que vous obtenez la même plante (ou dans ce cas, la même séquence de nombres aléatoires) chaque fois que vous utilisez cette graine.

Ici, `101` est la valeur de la graine. En définissant la graine sur `101`, nous nous assurons que la génération de nombres aléatoires suivante produira toujours la même séquence de nombres. Ceci est utile pour la reproductibilité, ce qui signifie que si quelqu'un d'autre exécute le même code avec la même graine, il obtiendra les mêmes résultats "aléatoires".

`print(np.random.randint(0,100,10))` génère puis affiche une séquence de nombres entiers aléatoires.

Ainsi, cette ligne générera 10 nombres entiers aléatoires entre 0 (inclus) et 100 (exclus), puis les affichera sur la console. Étant donné que nous avons défini la graine avec `np.random.seed(101)` précédemment, ces 10 nombres aléatoires seront toujours les mêmes chaque fois que le code est exécuté.

En résumé, ces deux lignes ensemble génèrent une séquence de nombres "pseudo-aléatoires". Ils semblent aléatoires, mais ils sont en réalité déterminés par la valeur initiale de la graine. Cela permet d'obtenir des résultats reproductibles lorsque vous travaillez avec l'aléatoire dans votre code.



---



array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

array([1, 2, 3])

##### 3

3

##### 1

1

##### 2.0

2.0

##### 2

2

##### array([1, 2, 3])

array([1, 2, 3])

In [ ]:
arr = np.random.randint(0,100,10)

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

##### 83

83

##### 8

8

##### 40.7

40.7

##### 1

1

##### array([[49, 83,  8, 29, 59], [34, 44, 72, 19, 10]])

array([[49, 83,  8, 29, 59],
       [34, 44, 72, 19, 10]])

##### array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49], [50, 51, 52, 53, 54, 55, 56, 57, 58, 59], [60, 61, 62, 63, 64, 65, 66, 67, 68, 69], [70, 71, 72, 73, 74, 75, 76, 77, 78, 79], [80, 81, 82, 83, 84, 85, 86, 87, 88, 89], [90, 91, 92, 93, 94, 95, 96, 97,98, 99]])

In [ ]:
mat = np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

##### 1

1

##### 3

3

##### array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

##### array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

##### array([[ 0,  1,  2], [10, 11, 12], [20, 21, 22]])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
my_filter = mat > 50

In [ ]:
# @title
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])